name: Minimal Node Setup
description: "Minimal safe Node.js action—sets up Node and installs dependencies"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "22"

    - run: yarn install --frozen-lockfile
      shell: bash
