name: Storybook

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  CLICOLOR: "1"
  PY_COLORS: "1"
  FORCE_COLOR: "1"
  IS_MASTER_BRANCH: ${{ github.ref == 'refs/heads/master' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get BRANCH_URL
        if: ${{ env.IS_MASTER_BRANCH != 'true' }}
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: echo "BRANCH_URL=$(sed -e 's/[^a-zA-Z0-9]/-/g' <<< ${BRANCH_NAME})" >> $GITHUB_ENV

      - name: Get DOMAINS
        if: ${{ env.IS_MASTER_BRANCH != 'true' }}
        run: |
          DOMAIN="https://kiwicom-w3shi-${BRANCH_URL}.surge.sh"
          echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV
          echo "DOMAIN_PLAYROOM=$DOMAIN/playroom" >> $GITHUB_ENV

      #- name: Deploy to staging
       # if: ${{ env.IS_MASTER_BRANCH != 'true' }}
       # run: yarn components deploy:surge ${DOMAIN} --token ${{ secrets.SURGE_TOKEN }}



      - name: Echo successful
        run: echo "✅ successful"
